# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
