# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0002_auto_20170326_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
