# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0008_auto_20170418_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='categoria',
        ),
        migrations.AddField(
            model_name='checklist',
            name='categoria',
            field=models.ManyToManyField(to='Avaliacao.Categoria'),
        ),
    ]
