# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0010_auto_20170419_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='categoria',
            new_name='selectCat',
        ),
    ]
