# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0011_auto_20170419_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='selectCat',
        ),
        migrations.AddField(
            model_name='checklist',
            name='selectCat',
            field=models.ManyToManyField(to='Avaliacao.Categoria'),
        ),
    ]
