# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0012_auto_20170420_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecklistCategoria',
            new_name='Checklist_Categoria',
        ),
    ]
