# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20170320_1451'),
        ('Avaliacao', '0013_auto_20170419_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario')),
                ('selectCat', models.ManyToManyField(to='Avaliacao.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='selectCat',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
