# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20170320_1451'),
        ('Avaliacao', '0014_auto_20170419_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario')),
                ('selectCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='check',
            name='selectCat',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
