# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0015_auto_20170420_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='catChk',
        ),
        migrations.AddField(
            model_name='checklist',
            name='categoria',
            field=models.ManyToManyField(through='Avaliacao.ChecklistCategoria', to='Avaliacao.Categoria'),
        ),
    ]
