# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0018_cadastrocheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocheck',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cadastrocheck',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria'),
            preserve_default=False,
        ),
    ]
