# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0020_auto_20170419_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='categoria',
        ),
        migrations.AddField(
            model_name='checklist_categoria',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Checklist'),
        ),
    ]
