# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0021_auto_20170419_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_categoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='checklist_categoria',
            name='checklist',
        ),
        migrations.AddField(
            model_name='checklist',
            name='categoria',
            field=models.ManyToManyField(to='Avaliacao.Categoria'),
        ),
        migrations.DeleteModel(
            name='Checklist_Categoria',
        ),
    ]
