# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20170320_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='metas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
