# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(blank=True, choices=[('ESPECIALISTA', 'Especialista'), ('AVALIADOR', 'Avaliador')], max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
