# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20170317_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(max_length=18),
        ),
    ]
