# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20170319_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('ESPECIALISTA', 'Especialista'), ('AVALIADOR', 'Avaliador')], max_length=18),
        ),
    ]
