# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0005_auto_20170418_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='data',
        ),
    ]
