# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0006_remove_checklist_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='categorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria'),
            preserve_default=False,
        ),
    ]
