# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0008_auto_20170419_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.CharField(max_length=255)),
                ('diretrizes', models.CharField(max_length=255, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='questao',
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
    ]
