# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0009_auto_20170419_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='categoria',
        ),
        migrations.AddField(
            model_name='checklist',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria'),
            preserve_default=False,
        ),
    ]
