# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0013_auto_20170420_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategoriaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist_categoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='checklist_categoria',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='categoria',
            field=models.ManyToManyField(through='Avaliacao.ChecklistCategoriaa', to='Avaliacao.Categoria'),
        ),
        migrations.DeleteModel(
            name='Checklist_Categoria',
        ),
        migrations.AddField(
            model_name='checklistcategoriaa',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Checklist'),
        ),
    ]
