# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20170320_1451'),
        ('Sistema', '0003_auto_20170324_1625'),
        ('Avaliacao', '0015_auto_20170420_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=80)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao_Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Avaliacao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='responsavel',
            field=models.ManyToManyField(through='Avaliacao.Avaliacao_Responsavel', to='Usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Sistema'),
        ),
    ]
