# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0016_auto_20170421_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=3)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Avaliacao')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Checklist')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.Questoes')),
            ],
        ),
    ]
