# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0017_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nome',
            field=models.CharField(default='Teste', max_length=80),
            preserve_default=False,
        ),
    ]
